### PR TITLE
Fix compatibility with Rails 7

### PR DESCRIPTION
**Pull request by n-rodriguez**

### CODE REVIEW

**Comment by bdarcet** [comment]
👋 @n-rodriguez thanks for the PR.
It looks like it triggered a new issue in the CI 
https://app.travis-ci.com/github/OpenGems/redis_web_manager/jobs/585480901

```
Failure/Error: require 'sprockets/railtie'

LoadError:

  cannot load such file -- sprockets/railtie
```
I think the error is triggered by the `require "sprockets/railtie"` that are done [here](https://github.com/OpenGems/redis_web_manager/blob/master/bin/rails#L19) and [here](https://github.com/OpenGems/redis_web_manager/blob/master/spec/dummy/config/application.rb#L8) (probably the later). WDYT ?

**Review by bdarcet — APPROVED** [review]

**Comment by n-rodriguez** [comment]
Hi there! Any news?

**Comment by n-rodriguez** [comment]
ping @bdarcet

**Comment by n-rodriguez** [comment]
@bdarcet can you explain me the point of making a PR if you merged your own one : https://github.com/OpenGems/redis_web_manager/commit/b5f4638c2f93e7fe30a3463bef4f125a3761bcba

**Comment by n-rodriguez** [comment]
@BorisBresciani that's not very fair / nice / whatever. that's not open source

**Comment by bdarcet** [comment]
Hi there, this project hasn't been maintained for a while. I think there was just a miscommunication between maintainers :) 
Sorry about what happened

**Pull request closed without merging**
